### ISSUE TITLE
No artifact files found at /home/circleci/project/scanResults/

### ISSUE THREAD

**Issue by mattvanstone** [PaloAltoNetworks/prisma-cloud-circleci-orb#5]
## Describe the bug

The store_artifacts step results in `No artifact files found at /home/circleci/project/scanResults/scan.csv` because the scan script uses a directory created with `mktemp -d scanResults.XXXXXXXX`.

## Expected behavior

The scan.csv file should be attached to the CircleCI job.

## Current behavior

No file is attached with the output message `No artifact files found at /home/circleci/project/scanResults/scan.csv`

## Possible solution

As a workaround I created an extra step to move the file into the proper location, and then I run store_artifacts again to store it.
```
      - run:
          name: artifacts fix
          command: |
            RESULTS_DIR=`ls -d scanResults*`
            mkdir scanResults
            cp $RESULTS_DIR/scan.csv scanResults
      - store_artifacts:
          path: scanResults/scan.csv
```

This could be integrated into the end of the iac_scan command to put the file in the right directory before the store_artifacts job is run.

## Steps to reproduce

1. Create a CircleCI job that uses the iac_scan command. I assume this will also occur if you use the iac_scan job.
2. Run the pipeline

Here is my job without the fix I implemented:
```
  prisma_scan:
    executor: prisma
    description: Prisma Cloud IaC Scan
    parameters:
      access_key:
        description: Prisma Cloud Access Key
        type: env_var_name
        default: prisma_cloud_access_key
      secret_key:
        description: Prisma Cloud Secret Key
        type: env_var_name
        default: prisma_cloud_secret_key
      prisma_cloud_api_url:
        description: Prisma Cloud Server Url
        type: string
        default: $prisma_cloud_console_url
      terraform_variable_filenames:
        description: Comma separated list of filenames containing Terraform variables.
        type: string
        default: ""
      templates_directory_path:
        description: Directory path where IaC templates are stored.
        type: string
        default: .
      failure_criteria_high_severity:
        description: Provide failure threshold for high severity security issues.
        type: integer
        default: 0
      failure_criteria_medium_severity:
        description: Provide failure threshold for medium severity security issues.
        type: integer
        default: 0
      failure_criteria_low_severity:
        description: Provide failure threshold for low severity security issues.
        type: integer
        default: 0
      failure_criteria_operator:
        description: Provide operator for high, medium, low severity failure thresholds.
        type: string
        default: or
      tags:
        description: Provide the Tags for the repo.
        type: string
        default: ""
    steps:
      - attach_workspace:
          at: .
      - prisma/auth:
          access_key: <<parameters.access_key>>
          secret_key: <<parameters.secret_key>>
          prisma_cloud_api_url: <<parameters.prisma_cloud_api_url>>        
      - prisma/iac_scan:
          terraform_variable_filenames: <<parameters.terraform_variable_filenames>>
          templates_directory_path: <<parameters.templates_directory_path>>
          failure_criteria_high_severity: <<parameters.failure_criteria_high_severity>>
          failure_criteria_medium_severity: <<parameters.failure_criteria_medium_severity>>
          failure_criteria_low_severity: <<parameters.failure_criteria_low_severity>>
          failure_criteria_operator: <<parameters.failure_criteria_operator>>
          tags: <<parameters.tags>>
```

## Screenshots

![Screenshot 2020-11-19 172311](https://user-images.githubusercontent.com/12474847/99740292-ee31e480-2a8b-11eb-9f76-2421a7a0809b.png)

## Context

Just looking to fix a function that is not working.

## Your Environment

- CircleCI Cloud
- orb version 2.2.0
